# Generated by Django 3.2.8 on 2022-08-20 07:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_datejoined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattleTagID', models.CharField(max_length=250)),
                ('cattleTagPosition', models.CharField(max_length=250)),
                ('cattleType', models.CharField(max_length=250)),
                ('cattleStatus', models.CharField(max_length=250)),
                ('cattleHornStatus', models.CharField(max_length=250)),
                ('cattleBreed', models.CharField(max_length=250)),
                ('cattleComment', models.CharField(max_length=250)),
                ('cattleDateRecorded', models.DateField(default=datetime.date.today)),
                ('cattleAttachment', models.ImageField(null=True, upload_to='animal/cattle/')),
                ('cattleRaisedOrPurchased', models.CharField(max_length=250)),
                ('cattleCommercialNote', models.CharField(max_length=250)),
                ('cattleBirthDate', models.DateField(blank=True, null=True)),
                ('cattleBirthWeight', models.FloatField()),
                ('cattleWeaningStatus', models.CharField(max_length=250)),
                ('cattleDam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cattle_Dam', to='animal.cattle')),
                ('cattleLastUpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('cattleSire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cattle_Sire', to='animal.cattle')),
            ],
            options={
                'db_table': 'Cattle',
            },
        ),
        migrations.CreateModel(
            name='CattleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cattleGroupName', models.CharField(max_length=250)),
                ('cattleGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.cattle')),
            ],
            options={
                'db_table': 'CattleGroup',
            },
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheepTagID', models.CharField(max_length=250)),
                ('sheepTagPosition', models.CharField(max_length=250)),
                ('sheepType', models.CharField(max_length=250)),
                ('sheepStatus', models.CharField(max_length=250)),
                ('sheepHornStatus', models.CharField(max_length=250)),
                ('sheepBreed', models.CharField(max_length=250)),
                ('sheepComment', models.CharField(max_length=250)),
                ('sheepDateRecorded', models.DateField(default=datetime.date.today)),
                ('sheepAttachment', models.ImageField(null=True, upload_to='animal/sheep/')),
                ('sheepRaisedOrPurchased', models.CharField(max_length=250)),
                ('sheepCommercialNote', models.CharField(max_length=250)),
                ('sheepBirthDate', models.DateField(blank=True, null=True)),
                ('sheepBirthWeight', models.FloatField()),
                ('sheepWeaningStatus', models.CharField(max_length=250)),
                ('sheepEwe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheep_Ewe', to='animal.sheep')),
                ('sheepLastUpdatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('sheepRam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheep_Ram', to='animal.sheep')),
            ],
            options={
                'db_table': 'Sheep',
            },
        ),
        migrations.CreateModel(
            name='SheepGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheepGroupName', models.CharField(max_length=250)),
                ('sheepGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.sheep')),
            ],
            options={
                'db_table': 'SheepGroup',
            },
        ),
        migrations.CreateModel(
            name='SheepGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_sheepID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.sheep')),
                ('sg_sheepGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.sheepgroup')),
            ],
            options={
                'db_table': 'SheepGrouping',
                'unique_together': {('s_sheepID', 'sg_sheepGroup')},
            },
        ),
        migrations.CreateModel(
            name='CattleGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_cattleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.cattle')),
                ('cg_cattleGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.cattlegroup')),
            ],
            options={
                'db_table': 'CattleGrouping',
                'unique_together': {('c_cattleID', 'cg_cattleGroup')},
            },
        ),
    ]
