# Generated by Django 3.2.8 on 2022-08-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattlegroup',
            name='cattleGroupID',
        ),
        migrations.RemoveField(
            model_name='sheepgroup',
            name='sheepGroupID',
        ),
    ]
