# Generated by Django 3.2.8 on 2022-08-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20220820_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='cattleOfferPrice',
            field=models.FloatField(default=0),
        ),
    ]
