# Generated by Django 3.2.8 on 2022-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0003_cattle_cattleofferprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='cattleBirthWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='cattleBreed',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='cattleComment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='cattleCommercialNote',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cattle',
            name='cattleOfferPrice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
