# Generated by Django 3.2.8 on 2022-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20220821_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='sheepBirthWeight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='sheepBreed',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='sheepComment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='sheepCommercialNote',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
