# Generated by Django 3.2.8 on 2022-08-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20220821_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='sheepOfferPrice',
            field=models.FloatField(default=0, null=True),
        ),
    ]
