# Generated by Django 3.2.8 on 2022-08-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0006_sheep_sheepofferprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='sheepEwe',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='sheepRam',
        ),
        migrations.AddField(
            model_name='sheep',
            name='sheepDam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheep_Dam', to='animal.sheep'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='sheepSire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sheep_Sire', to='animal.sheep'),
        ),
    ]
