# Generated by Django 3.2.8 on 2022-08-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150, unique=True)),
                ('staffID', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('dateOfBirth', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('maritalStatus', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('userRole', models.CharField(max_length=150)),
                ('media', models.ImageField(default='', upload_to='uploads/')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
