# Generated by Django 3.2.8 on 2022-08-17 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220816_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dateJoined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
