# Generated by Django 3.2.8 on 2022-08-26 04:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0007_auto_20220823_1735'),
        ('user', '0003_user_datejoined'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleTicketInvoice', models.CharField(max_length=250, null=True)),
                ('saleMarketingCost', models.FloatField(default=0, null=True)),
                ('soldToCustomer', models.CharField(max_length=255)),
                ('saleComment', models.TextField(blank=True, null=True)),
                ('saleDate', models.DateField(blank=True, null=True)),
                ('saleRecordedDate', models.DateField(default=datetime.date.today)),
                ('saleAttachment', models.FileField(null=True, upload_to='financial/saleTicket/')),
                ('saleLastUpdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleTicketLastUpdatedBy', to='user.user')),
                ('saleRecordedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleTicketRecordedBy', to='user.user')),
            ],
            options={
                'db_table': 'SaleTicket',
            },
        ),
        migrations.CreateModel(
            name='SoldSheep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_pricePerKg', models.FloatField()),
                ('ss_salePrice', models.FloatField()),
                ('ss_saleWeight', models.FloatField()),
                ('ss_saleTicket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheepSaleTicket', to='financial.saleticket')),
                ('ss_sheep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheepSold', to='animal.sheep')),
            ],
            options={
                'db_table': 'SoldSheep',
            },
        ),
        migrations.CreateModel(
            name='SoldCattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_pricePerKg', models.FloatField()),
                ('sc_salePrice', models.FloatField()),
                ('sc_saleWeight', models.FloatField()),
                ('sc_cattle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattleSold', to='animal.cattle')),
                ('sc_saleTicket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattleSaleTicket', to='financial.saleticket')),
            ],
            options={
                'db_table': 'SoldCattle',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incomeItem', models.CharField(max_length=250)),
                ('incomeAmount', models.FloatField(default=0, null=True)),
                ('incomeCategory', models.CharField(max_length=250, null=True)),
                ('incomeCustomer', models.CharField(blank=True, max_length=255, null=True)),
                ('incomeInvoice', models.CharField(max_length=250, null=True)),
                ('incomeMadeDate', models.DateField(blank=True, null=True)),
                ('incomeRecordDate', models.DateField(default=datetime.date.today)),
                ('incomeAttachment', models.FileField(null=True, upload_to='financial/income/')),
                ('incomeLastUpdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomeLastUpdatedBy', to='user.user')),
                ('incomeRecordedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomeRecordedBy', to='user.user')),
            ],
            options={
                'db_table': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseName', models.CharField(max_length=250)),
                ('expenseAmount', models.FloatField(default=0, null=True)),
                ('expenseCategory', models.CharField(max_length=250, null=True)),
                ('expenseNote', models.TextField(blank=True, null=True)),
                ('expenseMadeDate', models.DateField(blank=True, null=True)),
                ('expenseRecordDate', models.DateField(default=datetime.date.today)),
                ('expenseAttachment', models.FileField(null=True, upload_to='financial/expense/')),
                ('expenseLastUpdatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenseLastUpdatedBy', to='user.user')),
                ('expenseMadeBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenseMadeBy', to='user.user')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
    ]
