# Generated by Django 3.2.8 on 2022-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_auto_20220827_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleticket',
            name='saleTicketInvoiceStatus',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
