# Generated by Django 3.2.8 on 2023-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_saleticket_saleticketinvoicestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleticket',
            name='saleTotalAmount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
