# Generated by Django 3.2.8 on 2022-08-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_datejoined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=250)),
                ('taskPriority', models.CharField(max_length=250)),
                ('taskCategory', models.CharField(max_length=250)),
                ('taskDetails', models.CharField(max_length=250)),
                ('taskDueDate', models.DateField()),
                ('taskCompletionStatus', models.CharField(max_length=250)),
                ('taskAttachment', models.FileField(null=True, upload_to='task/')),
                ('taskAssignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskAssignee', to='user.user')),
                ('taskAssigner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskAssigner', to='user.user')),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
