# Generated by Django 3.2.8 on 2022-08-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentName', models.CharField(max_length=150)),
                ('equipmentMake', models.CharField(max_length=150, null=True)),
                ('equipmentModel', models.CharField(max_length=150, null=True)),
                ('equipmentYear', models.CharField(max_length=150, null=True)),
                ('equipmentSerialID', models.CharField(max_length=150, null=True, unique=True)),
                ('equipmentAcquiredDate', models.DateField(blank=True, null=True)),
                ('equipmentLastMaintenance', models.DateField(blank=True, null=True)),
                ('equipmentColor', models.CharField(max_length=150, null=True)),
                ('equipmentLocation', models.CharField(max_length=150)),
                ('equipmentPrice', models.FloatField(max_length=150, null=True)),
                ('equipmentPurchasedFrom', models.CharField(max_length=150, null=True)),
                ('equipmentNotes', models.CharField(max_length=150, null=True)),
                ('equipmentStatus', models.CharField(max_length=150, null=True)),
                ('equipmentPhoto', models.ImageField(default='', null=True, upload_to='equipment/')),
            ],
            options={
                'db_table': 'Equipment',
            },
        ),
    ]
