# Generated by Django 3.2.8 on 2022-08-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_datejoined'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquimentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUsed', models.DateField(blank=True, null=True)),
                ('statusUsage', models.CharField(max_length=250)),
                ('usageInfo', models.CharField(max_length=250)),
                ('equipmentID_equip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('usedBy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'EquipmentUsage',
            },
        ),
    ]
