# Generated by Django 3.2.8 on 2022-08-18 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_auto_20220818_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentusage',
            name='equipmentID_equip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usedEquipment', to='equipment.equipment'),
        ),
    ]
